baseURL = "http://example.org/"
languageCode = "en-us"
title = "UCLA Dataverse Documentation"

theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant="ucla"